### ISSUE TITLE
Epic: Aftermath actions of Open Source

### ISSUE THREAD

**Issue by flikka** [equinor/gordo#221]
Please add elements that we need to do (tasks) here, or make issues and label them with open source. 

The key approvals for making Gordo open source is as far as flikka knows to get approval from relevant line managers, for Gordo flikka believes this to be the Data Science line, and the IT line.  VP of data science and SIB leader are positive.

Things to do:

- [x] Decide on licensing - discuss with Chief Eng IT representatives.
- [x] Make better "overall" documentation, architecture drawing or flow. Issues #137 & #323 
- [x] Add more example data?
- [x] Readthedocs
- [x] Add coveralls or similar? #156 
- [x] Push to PyPi (https://github.com/equinor/gordo-components/pull/303)
- [x] Move stuff from infrastructure into components? Maybe keep equinor specific stuff in infrastructure and move e.g. the workflow template into components? At least it makes sense to open source it as well. (#534) 
- [x] In workflow template: parameterize the docker container registry name, which today is hard-coded to auroradevacr (#548)

**Comment by epa095** [comment]
We just did it

**Comment by milesgranger** [comment]
Think this was more serving as a tracking issue, no? Lots of unchecked boxes left.

**Comment by flikka** [comment]
I agree, think that was a bit premature, look - a new title!
