### ISSUE TITLE
Epic: Adapt model-builder for hyperparameter tuning (grid search)

### ISSUE THREAD

**Issue by epa095** [equinor/gordo#29]
There are a few things which can be done to make the model-builder useful for hyperparameter tuning with e.g. katib.
- Ensure that we print out relevant metrics on the format `Metric: Value` to stdout
- Allow overriding model-parameters through environment variables or parameters. The solution to this should/will depends on Statoil/gordo-infrastructure#65

---

- [x] Model builder - Toggle option to not save a model (https://github.com/equinor/gordo-components/issues/244)
- [x] Model builder - Output scoring to stdout (https://github.com/equinor/gordo-components/issues/243)
- [ ] Model builder - Ability to customize scoring (https://github.com/equinor/gordo-components/issues/242)
- [x] Template the model config - (https://github.com/equinor/gordo-components/issues/241)
