### ISSUE TITLE
Parameter logging during model training

### ISSUE THREAD

**Issue by henrikny** [equinor/gordo#649]
These are the different model parameters we want to log under training.

### Metrics
For each scaled variable and for each time series cross-validation split:
- [x] Mean squared errors
- [x] Explained variance
- [x] R^2

### Metadata
- [x] Start and end date for each fold.
- [x] Gordo model name (tilstandomatic_model_id + tilstandomatic_model_tag) = model_id
- [x] Unique model version (model_id + hash of model config?)
- [x] Complete config information (parsed yaml)
- [x] Data query duration
- [x] Training time duration

**Comment by ryanjdillon** [comment]
Start and end date to CV folds added in #785, so this one should be all wrapped up. Closing.
