### ISSUE TITLE
Gordo production (aka prediction) output

### ISSUE THREAD

**Issue by henrikny** [equinor/gordo#650]
### Model output

Once in production, the following values and variables should be returned:
(n observations, m input variables)

- [x] `tag_pred`: Model predictions original scale (n x m).
- [x] `tag_scaled_res`: Residuals based on scaled inputs and predictions (n x m).
- [x] `tag_abs_res`: Absolute residuals based on **unscaled** inputs and predictions (n x m).
- [x] `model_mse`: Based on the squared residuals from the **scaled** inputs and predictions, calculate the _average over all variables_ for _each point in time_ (n x 1).
- [x] Current _total anomaly_ (scalar) based on the Frobenius (`numpy.linalg.norm`) norm can be dropped.

**Comment by milesgranger** [comment]
It seems like almost all of this, or at least certainly the "model output", can be implemented as a separate [`AnomalyDetectorBase`](https://gordo-components.readthedocs.io/en/latest/components/model/anomaly.html#gordo_components.model.anomaly.diff.DiffBasedAnomalyDetector) model or updating the current [`DiffBasedAnomalyDetector`](https://gordo-components.readthedocs.io/en/latest/components/model/anomaly.html#gordo_components.model.anomaly.diff.DiffBasedAnomalyDetector)

**Comment by flikka** [comment]
So @henrikny, @milesgranger have worked on a PR that solves a lot of the things you mention here: https://github.com/equinor/gordo-components/pull/673

Some issues / questions:
* The output today + this PR, from the "anomaly" endpoint is:
    * The (original) model input (aka the X values, in the tags list), called model-input, for each tag
    * The calculated output (aka the Yhat values, from the target_tag_list list) in the original scale, called model-output, for each output tag.
    * tag-anomaly values for each output-tag. These are _normalized_/scaled values based on the DiffBasedAnomalyDetector. The reason for scaling is that they are then more easily comparable.
    * total-anomaly, one value per timestamp. This is just all the tag-anomalies, also on scaled data.
    * (new): anomaly-confidence: one value per output-tag, where the 6 point min sliding window was used to device a threshold (not reported) and then based on these thresholds, we produce the anomaly-confidence. The `anomaly-confidence` is just the a tag's anomaly, divided by the threshold devised.
        * This means that it allows for a bit more flexibility, an `anomaly-confidence` at 1.0 or higher, means that the anomaly is above the threshold. But by providing this, the users/client/UX can allow for increasing or decreasing the alarm limits, or use categories like "low/medium/high/insane" alarms.

So @henrikny - the PR in question will solve the parts of this issue that we found most important to do first, but _not all_ of the artifacts you mention are currently being implemented.
