### ISSUE TITLE
Epic: user stories related to querying model building results

### ISSUE THREAD

**Issue by flikka** [equinor/gordo#720]
- [ ] As a SME I want to analyze the results of the building and training of my models and groups of models (#723)
- [ ] As a SME I want to plot run results for a model or groups of models (#724)
- [ ] As a SME I want to have access  to the history of runs using a simple connection string (#725)
- [ ] As a SME I want to access to the data quickly from any visualization tool (#726)
- [ ] As a SME I want to navigate easily thru the history of Gordo runs (#727)
- [ ] As a SMR I want to identify clearly the results, metrics, metadata of the Gordo runs (#728)
- [ ] As a SME I want to be able to join run results to external hierarchies, data models (#729)
- [ ] As a SME I want to share and publish run results and reports to an audience (#730)

**Comment by flikka** [comment]
We'll revisit this later when the important things pop up again.
