### ISSUE TITLE
Gordo production output: Evaluation of threshold and creation of health index

### ISSUE THREAD

**Issue by henrikny** [equinor/gordo#737]
### Threshold evaluation

**Complete model**

For each model in production, apply the following scheme.

- [x] 1. Fetch the model thresholds (described in #736) from each of the three splits.
- [x] 2. Calculate the `average_threshold` over all splits.
- [x] 3. Fetch the `model_mse` (described in #650).
- [x] 4. Compare the vector against the known threshold and return a vector of health indicator [`model_mse` / `average threshold`].

**Individual input variable**

For every variable of every model in production, apply the following scheme:

- [x] 1. Fetch the individual input variable thresholds (described in #736) from each of the three splits.
- [x] 2. Calculate the `average_threshold` over all splits.
- [x] 3. Fetch the `tag_abs_res` (described in #650).
- [x] 4. Compare the vector against the known threshold and return a vector of health indicator [`tag_abs_res` / `average threshold`].

### Health indicator smoothing

The threshold evaluation is conveniently evaluated in Gordo for now, and is in practice a part of the Gordo output.
A smoothing of the health indicator is actually wanted, which applies a rolling look-back-window of size 6 which selects the minimum.
This should be in place for the complete model as well as for each individual reconstructed input variable.

To be able to create this smoothed health indicator by a look-back-window of six, additional points need to be fetched.

For given
- start timestamp t_1
- stop timestamp t_n and
- resolution r = delta[t_i] = t_i - t_[i-1] (e.g. 10min),
the vector length of the calculated metrics is (t_stop - t_start) / r = n (e.g. 24h / 10min = 144).

Fetch |T| = n + 5 data points needed at T = {t_-5, ... , t_-1, t_1, ..., t_n}.

It is unclear where this logic should reside for now, or if it should be considered for the November-2019 milestone.
In future implementations, this logic should reside outside Gordo, as more complicated factors might be added to the evaluation of the thresholds.
