### ISSUE TITLE
EPIC: Project revision between client and server.

### ISSUE THREAD

**Issue by epa095** [equinor/gordo#744]
**Problem:**
After a gordo project has been re-applied / recreated there are a time where we are inconsistent all over. 
- Watchman serves a project version, and also metadata. But it does currently not guarantee that the metadata it serves holds for the models of that exact version(!). This should be fixed. But for that to be fixed it needs to be able to communicate with the server what version if wants metadata for.
- The client has metadata it has fetched from watchman. If the previous point is fixed then it can know that the metadata is correct for that exact project version. But when it asks the server the server might or not be on the same version. If we are (unreasonably) lucky the signature of the model has changed so things will crash, and if we are unlucky we will just serve data with the wrong (ton old or too new) model.  So: The client should be able (forced?) to send a project version together with the request, and be guaranteed that if it gets a 200 OK then the data was applied on exactly that version of the model. 

**Subtasks:**
- [x] Server #745: Accept a project version parameter / header whatever with requests (to predict / anomaly / metadata), and if that is provided then only return 200 OK with a result if it can be served from that exact version. I propose we try to serve old versions in a "best effort", so we can serve old models, but if we are not able to resolve a version we return some other code than 500. Maybe a `410 Gone`. 
- [X] Server have endpoint for available revisions (#775)
- [X] Server have endpoint to list models by revision (#776)
- [x] Watchman #746: Ensure that the project version field in the metadata is consistent with the metadata collected/served.
- [x] Client #747:  Send the project_version together with the data to the server. Handle the possible 410 response code by updating its metadata from watchman.
