### ISSUE TITLE
Tracking issue: Reporters & feature gates.

### ISSUE THREAD

**Issue by milesgranger** [equinor/gordo#868]
Problem
-----------
We are essentially logging/reporting machines resulting from builds in two different ways (mlflow, and server-to-sql script) to two different sources.

- This causes any users of gordo to depend on these.
- Bloats our dependencies, which aside from being 'bad' also causes readthedocs to fail from memory consumption.
- Non-uniform way of implementing the logging/reporting machines when they are built.

Solution
-----------

- [x] Introduce concept of `Reporter` for postgres, which can be included in a Machine's runtime and will be called after the machine is built. (#865)

- [x]  Do the same for ML Flow logging. (#866)

- [ ] Place specific reporter requirements behind feature gates using `extras_require`, this will include only minimal deps (ie. excludes postgres and mlflow reporting dependencies) so _hopefully_ will put us back under memory use. (#867)
